# Generated by Django 5.0.6 on 2024-06-01 20:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='thumb_videos')),
                ('descricao', models.TextField(max_length=200)),
                ('categoria', models.CharField(choices=[('JOCA', 'Joca'), ('JUAN', 'Juan'), ('EMDUPLA', 'Em Dupla'), ('ESCOLA', 'Na escola'), ('EXTRAS', 'Extras')], max_length=10)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
